### ISSUE TITLE
onStart事件

### ISSUE THREAD

**Issue by readpan** [haroel/ezaction#1]
请问有开始tween时的事件吗?类似onStart这种

**Comment by haroel** [comment]
你好，这几天忙其他事情没能及时看到邮件。

 最新版本 onStart 回调已经加上了，这个回调是HAction都有的方法，tween也就自然支持了。

可以查看d.ts

   //每次act开始执行回调, 如果repeat 三次，则onComplete回调三次
     act.onUpdate(function( action )
     {
     });

**Comment by readpan** [comment]
谢谢您~ :)
